sudo: false
dist: trusty
language: perl
perl:
- '5.30'
- '5.14'
before_install:
- git config --global user.name "TravisCI"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla
- cpanm --quiet --notest Test::Kwalitee
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest Dist::Zilla::App::Command::cover
- dzil authordeps | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest --skip-satisfied
- dzil listdeps --author | cpanm --quiet --notest --skip-satisfied
- export AUTOMATED_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
- dzil listdeps | grep -vP '[^\w:]' | cpanm --quiet --notest --skip-satisfied
script:
- dzil smoke --release --author
after_success:
- dzil cover -outputdir cover_db -report coveralls
notifications:
  slack:
    secure: ofjNjhd8p+fv9IUKdIC3+PeIki0zwMH6p/CDK+5QyRKDroNe01N98TqZAo0VLAlwTDR0ZNl/DkuPwiC0Q8K/G3dokWLyx14S5hepfpzottI05y1k1pQ/Ag5biQ5QkUvtV4XVRrH/haEdBj9QPslhL8wcwv/Zc6If4ZsMC3KaDfk=
