#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Date-Holidays-Abstract
version:      0.02
version_from: lib/Date/Holidays/Abstract.pm
installdirs:  site
requires:
    Test::Pod::Coverage:           0.08
    Class::Virtual:                0
    Test::More:                    0
    Test::Pod:                     0.95
    File::Find:                    0
    File::Spec:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
