---
name: Date-Holidays-Abstract
version: 0.05
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
abstract: an abstract class for Date::Holidays::* modules
license: artistic
resources:
  license: http://opensource.org/licenses/artistic-license.php
requires:
  Class::Virtual: 0
  Test::Harness: 0
  Test::More: 0
provides:
  Date::Holidays::Abstract:
    file: lib/Date/Holidays/Abstract.pm
    version: 0.05
no_index:
  directory:
    - t
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
