name: Dist::Zilla Action
on: push

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Installing dependencies using cpanm and cpanfile"
        uses: jonasbn/github-action-perl-dist-zilla@master
        with:
          dzil-command: "cpanm --installdeps ."
      - name: "Testing distribution with dzil"
        #uses: jonasbn/github-action-perl-dist-zilla@master
        with:
          dzil-command: "dzil test --all"
