name: Dist::Zilla Action
on: push

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: dzil run
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: jonasbn/github-action-perl-dist-zilla@master
        with:
          dzil-command: dzil listdeps | cpanm
      - name: Test the distribution
        uses: jonasbn/github-action-perl-dist-zilla@master
        with:
          dzil-command: dzil test --all
