name: Dist::Zilla Action
on: push

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install dependencies and test the distribution"
        uses: jonasbn/github-action-perl-dist-zilla@master
      - run: 'dzil listdeps | cpanm'
      - run: 'dzil test --all'
