name: Dist::Zilla Action
on: push

jobs:
  dzil:
    runs-on: ubuntu-latest
    name: "dzil run"
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Installing dependencies using cpanm and cpanfile and testing distribution with dzil"
        uses: jonasbn/github-action-perl-dist-zilla@master
